version: '3'

services:
  ftpd-server:
    container_name: ftpd-server
    image: stilliard/pure-ftpd:hardened
    ports:
      - 21:21
      - 20:20
      - 30000-30009:30000-30009
    volumes:
      - './ftp/data:/home/username/'
      - './ftp/pass:/etc/pure-ftpd/passwd'
    network_mode: host
    environment:
      FTP_USER_NAME: "admin"
      FTP_USER_PASS: "admin"
      FTP_USER_HOME: "/home/admin"
    restart: always