resource_types:
  - name: postman
    type: docker-image
    source:
      repository: atzawada/concourse-postman-resource

  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource

resources:
  - name: git-repo
    type: git
    webhook_token: token
    source:
      uri: ((postman-resource-git-uri))
      branch: master
      username: ((git-username))
      password: ((git-password))
  
  - name: postman
    type: postman

  - name: email
    type: email
    source:
      smtp:
        host: ((email-host))
        port: ((email-port))
        username: ((email-username))
        password: TabM8teAppl!c8tion((email-password))
      from: ((email-address))
      to: [ ((email-recipient)) ]

jobs:
  - name: test-postman
    plan:
      - get: git-repo
      - put: postman
        params:
          script: "git-repo/test/postman_collection.json"
          folder: "git-repo/test"
          #env: "test-env"
          #data: "test-data"
          #globals: "test-globals"
          #iterations: 10
          #bail: true
          #silent: true
          #insecure: true
          #suppress_exit_code: true
          #ignore_redirects: true
          fail_job_on_test_failure: false
          dump_json_file_location: "git-repo/test/results"
          dump_html_file_location: "git-repo/test/results"
  
      - put: email
        params:
          subject_text: "Testing finished"
          body_text: "See attached file."
          attachment_globs: [ "postman/results.json" ]
