resource_types:
  - name: postman
    type: docker-image
    source:
      repository: atzawada/concourse-postman-resource

resources:
  - name: git-repo
    type: git
    webhook_token: token
    source:
      uri: ((git-repo))
      branch: master
      username: ((git-username))
      password: ((git-password))
  
  - name: postman
    type: postman

jobs:
  - name: test-postman
    plan:
      - get: git-repo
      - put: postman
        params:
          script: "git-repo/test/postman_collection_fails.json"
          scripts: "test-scripts"
          folder: "test-folder"
          #env: "test-env"
          #data: "test-data"
          #globals: "test-globals"
          iterations: 1
          #bail: true
          # silent: true
          # no_color: true
          insecure: true
          # suppress_exit_code: true
          ignore_redirects: true