resource_types:
  - name: postman
    type: docker-image
    source:
      repository: atzawada/concourse-postman-resource
  - name: ftp
    type: docker-image
    source:
      repository: aequitas/ftp-resource

resources:
  - name: git-repo
    type: git
    webhook_token: token
    source:
      uri: ((git-repo))
      branch: master
      username: ((git-username))
      password: ((git-password))
  
  - name: postman
    type: postman

  - name: ftp
    type: ftp
    source:
      regex: (?P<file>test(?P<version>[0-9\.]+).*\.txt)
      uri: ftp://((ftp-username)):((ftp-password))@172.17.0.3:21

jobs:
  - name: test-postman
    plan:
      - get: git-repo
      - put: postman
        params:
          script: "git-repo/test/postman_collection_fails.json"
          scripts: "test-scripts"
          folder: "git-repo/test"
          #env: "test-env"
          #data: "test-data"
          #globals: "test-globals"
          #iterations: 10
          #bail: true
          #silent: true
          #no_color: true
          #insecure: true
          #suppress_exit_code: true
          #ignore_redirects: true
          fail_job_on_test_failure: false
          dump_json_file_location: "git-repo/test/results"

      - put: ftp
        params:
          file: /tmp/build/put/git-repo/test/results